import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { CreateInvitationDto } from './dto/create-invitation.dto';
import { Response } from 'express';

@Injectable()
export class InvitationService {
    async generatePdf(createInvitationDto: CreateInvitationDto, res: Response) {
        const doc = new PDFDocument({
            size: 'A4',
            margin: 50,
        });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=invitation.pdf`);

        doc.pipe(res);

        
        doc
            .fillColor('#e67e22') 
            .fontSize(28)
            .text('IMENA FAMILY', { align: 'center' })
            .moveDown(0.5);

        doc
            .fillColor('#2c3e50')
            .fontSize(16)
            .text('Official Invitation', { align: 'center' })
            .moveDown(2);

    
        doc
            .fillColor('#2c3e50')
            .fontSize(22)
            .text(createInvitationDto.title, { align: 'center', underline: true })
            .moveDown(1.5);

        this.addDetail(doc, 'Date', createInvitationDto.date);
        this.addDetail(doc, 'Time', createInvitationDto.time);
        this.addDetail(doc, 'Location', createInvitationDto.location);

        doc.moveDown(1);
        doc
            .fontSize(18)
            .text('Agenda', { underline: true })
            .fontSize(12)
            .text(createInvitationDto.agenda)
            .moveDown(1);

        if (createInvitationDto.notes) {
            doc
                .fontSize(14)
                .text('Notes:')
                .fontSize(12)
                .text(createInvitationDto.notes);
        }

        
        doc
            .moveDown(4)
            .fontSize(10)
            .fillColor('#7f8c8d')
            .text('Generated by Imena Paper Pop - Celebrating Our Legacy', { align: 'center' });

        doc.end();
    }

    private addDetail(doc: any, label: string, value: string) {
        doc
            .fontSize(14)
            .fillColor('#7f8c8d')
            .text(`${label}: `, { continued: true })
            .fillColor('#2c3e50')
            .text(value)
            .moveDown(0.5);
    }
}
